server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeaway
    username: root
    password: 123456
    hikari:
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间(ms)
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #最大存活时间
      max-lifetime: 180000
      #连接超时时间
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

  main:
    #允许循环引用
    allow-circular-references: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.yeb.takeawayserver.pojo
  configuration:
    map-underscore-to-camel-case: false

# mybatis sql打印
logging:
  level:
    com.hb.takeawayserver.mapper: debug

#jwt配置
jwt:
  tokenHeader: Authorization
  secret: hb-secret
  expiration: 604800
  tokenHead: Bearer

